apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-props
spec:
  inputs:
    params:
      - name: name
        description: Simple text property for name
      - name: country
        description: Simple text property for country
      - name: test
        description: Simple text property for test
      - name: custom
        description: Simple text property for custom
  steps:
    - name: show-props
      image: ubuntu
      env:
        - name: NAME
          value: $(inputs.params.name)
        - name: COUNTRY
          value: $(inputs.params.country)
        - name: TEST
          value: $(inputs.params.test)   
        - name: CUSTOM
          value: $(inputs.params.custom)  
      command: ["/bin/bash", "-c"]
      args:
        - echo "Tekton Properties Test Run";
          echo "==========================";
          echo "name prop = $NAME";
          echo "country prop = $COUNTRY";
          echo "test prop = $TEST";
          echo "custom prop = $CUSTOM";
          echo "=========================="
